(() => {
  'use strict';

  const RETRIES = 3;
  const LOOKBACK_MINUTES = [25, 30, 35];
  const THRESHOLDS = { low: 20, normal: 50 };
  const fieldNames = {
    upSmall: ['上り・小型交通量', '上り小型交通量'], upLarge: ['上り・大型交通量', '上り大型交通量'], upUnknown: ['上り・車種判別不能交通量', '上り・車種判別不能'],
    downSmall: ['下り・小型交通量', '下り小型交通量'], downLarge: ['下り・大型交通量', '下り大型交通量'], downUnknown: ['下り・車種判別不能交通量', '下り・車種判別不能'],
    date: ['観測年月日'], time: ['時間帯'], timeCode: ['時間コード'], station: ['常時観測点コード']
  };

  function workerUrl() { return String(window.APP_CONFIG?.trafficVolumeWorkerUrl || '').trim().replace(/\/$/, ''); }
  function value(properties, names) { const key = names.find((name) => Object.prototype.hasOwnProperty.call(properties || {}, name)); return key ? properties[key] : null; }
  function metric(raw) { if (raw === null || raw === undefined || String(raw).trim() === '') return null; const number = Number(raw); return Number.isFinite(number) ? number : null; }
  function timeCode(minutesAgo) { const date = new Date(Date.now() - minutesAgo * 60 * 1000); date.setMinutes(Math.floor(date.getMinutes() / 5) * 5, 0, 0); const pad = (number) => String(number).padStart(2, '0'); return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}${pad(date.getHours())}${pad(date.getMinutes())}`; }
  function bboxFromMap(map) { const bounds = map.getBounds(); return [bounds.getWest(), bounds.getSouth(), bounds.getEast(), bounds.getNorth()]; }
  function buildUrl({ bbox, time, roadType = '3' }) { const cql = `"道路種別" = '${roadType}' AND "時間コード" = ${time} AND BBOX("ジオメトリ",${bbox.join(',')},'EPSG:4326')`; const params = new URLSearchParams({ minX: bbox[0], minY: bbox[1], maxX: bbox[2], maxY: bbox[3], time, roadType }); return `${workerUrl()}?${params.toString()}`; }
  function formatObservedAt(dateValue, timeValue, codeValue) { const raw = codeValue || `${dateValue || ''}${String(timeValue || '').padStart(4, '0')}`; const match = String(raw).match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})$/); return match ? `${match[1]}/${match[2]}/${match[3]} ${match[4]}:${match[5]}` : 'データなし'; }
  function parseFeature(feature) { const properties = feature.properties || {}; const coordinates = feature.geometry?.type === 'MultiPoint' ? feature.geometry.coordinates : [feature.geometry?.coordinates]; return coordinates.filter((point) => Array.isArray(point) && point.length >= 2).map((point) => { const values = { upSmall: metric(value(properties, fieldNames.upSmall)), upLarge: metric(value(properties, fieldNames.upLarge)), upUnknown: metric(value(properties, fieldNames.upUnknown)), downSmall: metric(value(properties, fieldNames.downSmall)), downLarge: metric(value(properties, fieldNames.downLarge)), downUnknown: metric(value(properties, fieldNames.downUnknown)) }; const metrics = Object.values(values).filter((item) => item !== null); const total = metrics.length ? metrics.reduce((sum, item) => sum + item, 0) : null; return { latitude: Number(point[1]), longitude: Number(point[0]), station: value(properties, fieldNames.station) || '観測地点', observedAt: formatObservedAt(value(properties, fieldNames.date), value(properties, fieldNames.time), value(properties, fieldNames.timeCode)), values, total, level: total === null ? 'no-data' : total <= THRESHOLDS.low ? 'low' : total <= THRESHOLDS.normal ? 'normal' : 'high' }; }); }
  function parseGeoJson(data) { return (Array.isArray(data.features) ? data.features : []).flatMap(parseFeature).filter((item) => Number.isFinite(item.latitude) && Number.isFinite(item.longitude)); }
  async function fetchJson(url) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10000); try { const response = await fetch(url, { headers: { Accept: 'application/json' }, cache: 'no-store', signal: controller.signal }); if (!response.ok) { const error = new Error(`HTTP_${response.status}`); error.status = response.status; throw error; } return await response.json(); } finally { clearTimeout(timer); } }
  async function fetchTrafficVolume({ map, roadType = '3' } = {}) { if (!workerUrl()) throw new Error('WORKER_URL_REQUIRED'); if (!map) throw new Error('MAP_REQUIRED'); const bbox = bboxFromMap(map); let lastError; for (let index = 0; index < Math.min(RETRIES, LOOKBACK_MINUTES.length); index += 1) { const observedCode = timeCode(LOOKBACK_MINUTES[index]); try { const data = await fetchJson(buildUrl({ bbox, time: observedCode, roadType })); const points = parseGeoJson(data); if (points.length) return { points, observedCode, fetchedAt: new Date().toISOString(), bbox, source: '交通量API（国土交通省/JARTIC）' }; lastError = new Error('NO_DATA'); } catch (error) { lastError = error; if (error.status === 401 || error.status === 403) break; } } throw lastError || new Error('NO_DATA'); }
  function createPopup(point) { const display = (number) => number === null ? 'データなし' : `${number}台`; const v = point.values; const total = point.total === null ? 'データなし' : `${point.total}台 / 5分`; const level = point.level === 'low' ? '交通量 少なめ' : point.level === 'normal' ? '交通量 普通' : point.level === 'high' ? '交通量 多め' : '交通量 判定不可'; return `<strong>交通量情報</strong><br>観測時刻：${point.observedAt}<hr><strong>上り</strong><br>小型：${display(v.upSmall)}　大型：${display(v.upLarge)}　その他：${display(v.upUnknown)}<br><strong>下り</strong><br>小型：${display(v.downSmall)}　大型：${display(v.downLarge)}　その他：${display(v.downUnknown)}<br><strong>合計：${total}</strong><br><span class="volume-level">${level}</span><br><small>観測地点：${point.station}<br>情報元：交通量API<br>取得時刻：${new Intl.DateTimeFormat('ja-JP', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date())}<br>※交通量をもとにした参考表示です。道路の通行可否や安全性を保証するものではありません。</small>`; }
  function createMarker(point) { return L.circleMarker([point.latitude, point.longitude], { radius: 6, color: '#1769aa', fillColor: '#55a9d6', fillOpacity: .9, weight: 2 }).bindPopup(createPopup(point)); }
  window.TrafficVolume = { fetchTrafficVolume, createMarker, buildUrl, timeCode, THRESHOLDS };
})();
